### ISSUE TITLE
EventsController is broken

### ISSUE THREAD

**Issue by shockey** [inaudiblecentaur/headcount#18]
Error:

```
[Error] Error: [ng:areq] Argument 'EventsController' is not a function, got undefined
```

I've assessed that the problem lies in `public/app/app.js`, on lines 20, 25, and 30 where EventsController is used.

My working theory at this time is that there is a syntax error in the controller that is preventing Angular from injecting it. Additionally, it appears that some code has accidentally been left out of the controller and left on its own at the bottom of the file.

**Comment by shockey** [comment]
Further reading for possible causes here: http://stackoverflow.com/questions/25895235/angularjs-error-ngareq-argument-homecontroller-is-not-a-function-got-und

**Comment by MyNameIsKir** [comment]
The link @kyleshockey posted hit the nail on the head. The pull request I just made fixes the issue.

**Comment by MyNameIsKir** [comment]
#19 fixed this. Closing issue.
